### ISSUE TITLE
Migrate from oh-my-zsh to prezto

### ISSUE THREAD

**Issue by huyvohcmc** [huyvohcmc/dotfiles#3]

**Comment by kutsan** [comment]
Migrate from oh-my-zsh to nothing. You shouldn't use configuration framework in my opinion. Try that way. Thank me later.

**Comment by kutsan** [comment]
And feel free to ask me anything. My timezone is UTC+3. Zsh is little hard to learn but once you grasp it, it becomes easy to tweak.

**Comment by huyvohcmc** [comment]
I'm not planning to learn zsh in the near future so migrating seems like a good improvement for me.
